"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var addIceCreamFlavors_1 = require("./models/addIceCreamFlavors");
var icecremflavor_1 = require("./models/icecremflavor");
var strawberry = new icecremflavor_1.default();
strawberry.name = "Strawberry";
strawberry.price = 2;
strawberry.isPopular = true;
strawberry.description = "It is delicious";
console.log(strawberry);
console.log(strawberry.getTotalPrice(4));
strawberry.printInfo();
var chocolate = new icecremflavor_1.default();
chocolate.name = "Chocolate";
chocolate.price = 3.9;
chocolate.isPopular = false;
chocolate.description = "It is super delicious";
console.log(chocolate);
console.log(chocolate.getTotalPrice(4));
chocolate.printInfo();
var banana = new icecremflavor_1.default();
banana.name = "Banana";
banana.price = 3.2;
banana.isPopular = true;
banana.description = "It is super duper delicious";
console.log(banana);
console.log(banana.getTotalPrice(4));
banana.printInfo();
var mango = new icecremflavor_1.default();
mango.name = "Mango";
mango.price = 5.3;
mango.isPopular = false;
mango.description = "It is super duper ultra delicious";
console.log(mango);
console.log(mango.getTotalPrice(4));
mango.printInfo();
var iceCreamFlavors = [strawberry, chocolate, banana, mango];
iceCreamFlavors.forEach(function (flavor) {
    if (flavor.isPopular) {
        console.log(flavor.name);
    }
});
(0, addIceCreamFlavors_1.default)(iceCreamFlavors);
